### ISSUE TITLE
原型对象上如何调用到原型链上的方法

### ISSUE THREAD

**Issue by MuYunyun** [mqyqingfeng/waterfall#1]
楼主大大，我大致看了下您的代码的实现，看到下面这行代码的时候有个疑问，为什么原型对象 Waterfall 上能调用其原型链上的 init 方法呢？是我漏了什么知识点吗，望提示 😄 
https://github.com/mqyqingfeng/waterfall/blob/239c21a62d0ca9db1c68ade7e0d3efa5b2d7d5c7/waterfall.js#L160

**Comment by mqyqingfeng** [comment]
@MuYunyun 关于这个问题，我们先抽离一个简单的 demo：

```js
function Person() {
   this.init();
}

Person.prototype.init = function() {
   console.log(1)
} 

var person = new Person(); // 1
```

关键就在于 new  的时候，到底发生了什么事情，这个可以参考 [JavaScript深入之new的模拟实现](https://github.com/mqyqingfeng/Blog/issues/13)，简单的来说, new 的时候，做了四件事情：

1. 创建一个新对象
2. 将新对象的原型设置为构造函数的 prototype 属性
3. 执行构造函数，将 this 指向该原型对象
4. 返回这个新对象

所以当我们 `new Person()` 的时候，到第三步会执行该构造函数，并将 this 指向内部创建的新对象，构造函数内部执行 `this.init()` 函数，因为在第二步的时候，就已经设置了这个新对象的原型，所以就会到原型中查找该方法

哪里没有讲清楚，欢迎留言交流哈~

**Comment by MuYunyun** [comment]
👍 感谢楼主的解答，一下子就切中了问题的要害，
```js
  function Waterfall() {
     this.init()
  }
  Waterfall.prototype.init = function() {}
  window.onload = Waterfall 
```
因为对 new 知识的未完全掌握，至使了在 window.onload 里调用 Waterfall 函数未找到 this.init(), this 指向了 window 了，再次感谢楼主，向楼主学习~
